version: "3.3"

services:
  moleculer-scaffold:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: moleculer-scaffold
    container_name: moleculer-scaffold
    env_file: docker-compose.env
    volumes:
      - .:/app
      - modules:/app/node_modules

volumes:
  modules:
    
networks:
  default:
    external:
      name: dev-utils
